# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties on https://modmuss50.me/fabric.html
minecraft_version=26.3
loom_version=1.18-SNAPSHOT
loader_version=0.19.5
fabric_api_version=0.161.0+26.3

# Mod Properties
mod_version=1.0.8
maven_group=fr.madu59
mod_id=better-compass

# Dependencies
# Mod Menu from https://modrinth.com/mod/modmenu/versions
modmenu_version=21.0.0